
services:
  registry:
    image: registry:2
    container_name: local-registry
    ports:
      - "5000:5000"
    profiles:
      - local-registry

  skopeo:
    image: quay.io/skopeo/stable:latest
    container_name: skopeo
    volumes:
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/sync-skopeo.sh:/sync.sh
    entrypoint: ["sh", "/sync.sh"]
    # depends_on:
    #  - registry
    profiles:
      - tools0

  oras:
    image: ghcr.io/oras-project/oras:v1.1.0
    container_name: oras
    volumes:
      - ./charts:/charts
    profiles:
      - tools1

  charts-syncer:
    image: bitnami/charts-syncer:latest
    container_name: charts-syncer
    volumes:
      - ./scripts/charts-syncer.yaml:/charts-syncer.yaml
    command: ["sync", "--config", "/charts-syncer.yaml"]
    profiles:
      - tools2