
services:
  registry:
    image: registry:2
    container_name: local-registry
    ports:
      - "5000:5000"
    profiles:
      - registry
    #environment:
    #   # --- Basic Authentication Configuration ---
    #   REGISTRY_AUTH: htpasswd
    #   REGISTRY_AUTH_HTPASSWD_REALM: "Registry Realm"
    #   REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
    #   # --- HTTPS (TLS) Configuration ---
    #  REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
    #  REGISTRY_HTTP_TLS_KEY: /certs/domain.key
    volumes:
    #   #- ./local_registry/data:/var/lib/registry # Persist registry data
    #   - ./local_registry/auth:/auth:ro          # (read-only)
     - ./local_registry/certs:/certs:ro 

  skopeo:
    image: my-skopeo-helm:latest
    build:
      context: ./skopeo-with-helm
      dockerfile: my-skopeo-helm.dockerfile
    container_name: skopeo
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./scripts/sync-skopeo.sh:/sync.sh
      - ./config/sync-config.yaml:/sync-config.yaml
      #- ./local_registry/certs/domain.crt:/etc/containers/certs.d/registry:5000/ca.crt
    entrypoint: ["sh", "/sync.sh"]
    # depends_on:
    #  - registry
    profiles:
      - tools0

  oras: # built into helm
    image: ghcr.io/oras-project/oras:v1.1.0
    container_name: oras
    profiles:
      - tools1

  charts-syncer:
    image: bitnami/charts-syncer:latest
    container_name: charts-syncer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/charts-syncer.yaml:/charts-syncer.yaml
      - ./registries.conf:/etc/containers/registries.conf:ro
    command: ["sync", "--config", "/charts-syncer.yaml","-v","3"]
    profiles:
      - tools2

  dregsy:
    image: xelalex/dregsy:0.5.2-ubuntu
    container_name: dregsy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/sync-dregsy.yaml:/config.yaml
    environment:
      - LOG_LEVEL=debug
    profiles:
      - tools3

  acions-runner:
    image: actions-runner:latest
    build:
      context: ./actions-runner
      dockerfile: actions-runner.dockerfile
    container_name: actions-runner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./scripts/sync_registries.sh:/sync.sh
      - ./scripts/test_functions.sh:/test-functions.sh
      - ./config/sync-config.yaml:/sync-config.yaml
      #- ./local_registry/certs/domain.crt:/etc/containers/certs.d/registry:5000/ca.crt
    entrypoint: ["sh", "/sync.sh"]
    # depends_on:
    #  - registry
    profiles:
      - runner