services:
  registry:
    image: registry:2
    container_name: local-registry
    ports:
      - "5000:5000"
    restart: always

  ubuntu-skopeo:
    build:
      context: ./skopeo-with-helm
      dockerfile: ubuntu-skopeo-helm.dockerfile
    container_name: ubuntu-skopeo
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./scripts:/ARISU/scripts
      - ./config:/ARISU/config
      - ./charts-syncer/charts-syncer.yaml:/home/runner/charts-syncer.yaml
      - ./charts-syncer/registries.conf:/etc/containers/registries.conf:ro
    depends_on:
      - registry
    command: ["tail", "-f", "/dev/null"]