# registry.example.com:
#     images:
#         busybox: []
#         redis:
#             - "1.0"
#             - "2.0"
#             - "sha256:0000000000000000000000000000000011111111111111111111111111111111"
#     images-by-tag-regex:
#         nginx: ^1\.13\.[12]-alpine-perl$
#     images-by-server:
#         alpine: ">= 3.12.0"
#     credentials:
#         username: john
#         password: this is a secret
#     tls-verify: true
#     cert-dir: /home/john/certs
quay.io:
    images:
        coreos/etcd:
            - v3.5.9
docker.io:
    images:
        alpine:
            - "3.22"
            - latest