
images:
  - source: docker.io/library/alpine:3.22
    # destination: myacr.azurecr.io/library/alpine:latest
    destination: localhost:5000/library/alpine:3.22
  - source: docker.io/library/alpine:3.16
    destination: localhost:5000/library/alpine:3.16

helm_charts:
  - name: hello-world-h
    repo: ./hello-world-h
    version: 0.1.0
    destination: localhost:5000/helm/hello-world-h

