
images:
  - source: docker.io/library/nginx:3.22
    destination: myacr.azurecr.io/library/nginx:latest
  - source: docker.io/library/nginx:3.16
    destination: myacr.azurecr.io/library/nginx:latest

helm_charts:
  - name: hello-world-h
    repo: ./hello-world-h
    version: 0.1.0
    destination: myacr.azurecr.io/helm/hello-world-h

