# Registry Configuration
registry:
  url: registry:5000
  user: admin
  password: admin

# Docker Images to Synchronize
dockerImages:
  - source: docker.io/library/alpine:3.22
    destinationPath: alpine:3.22
  - source: docker.io/library/alpine:3.16
    destinationPath: alpine:3.16
  - source: docker.io/grafana/grafana:12.0.2
    destinationPath: charts/grafana:12.0.2

# Helm Charts to Synchronize
helmCharts:
  - repoName: bitnami
    repoUrl: https://charts.bitnami.com/bitnami
    chartName: nginx
    chartVersion: 15.14.0
    destinationPath: charts/
  - repoName: kubernetes-ingress
    repoUrl: https://kubernetes.github.io/ingress-nginx
    chartName: ingress-nginx
    chartVersion: 4.13.0
    destinationPath: charts/