registry:
  url: registry:5000
  user: admin
  password: admin
dockerImages:
  - source: docker.io/library/alpine:3.22
    destinationPath: images/alpine
    version: "3.22"
  - source: docker.io/grafana/grafana
    destinationPath: images/grafana
    version: latest
helmCharts:
  - repoName: bitnami
    repoUrl: https://charts.bitnami.com/bitnami
    chartName: nginx
    chartVersion: 15.14.0
    destinationPath: charts/
  # - repoName: kubernetes-ingress
  #   repoUrl: https://kubernetes.github.io/ingress-nginx
  #   chartName: ingress-nginx
  #   chartVersion: 4.13.0
  #   destinationPath: charts/
