
images:
  - source: docker.io/library/alpine:3.22
    # target_repo: myacr.azurecr.io/library/alpine:latest
    target_repo: localhost:5000/library/alpine:3.22
  - source: docker.io/library/alpine:3.16
    target_repo: localhost:5000/library/alpine:3.16

helm_charts:
  - name: alpine
    version: 3.22
    source_repo: https://charts.bitnami.com/bitnami
    target_repo: charts
  - name: hello-world-h
    source_path: ./hello-world-h

